
# Hands-on Lab: Loading data with Pandas

Estimated time needed: **30** minutes

## Objectives

After completing this lab you will be able to:

*   Use Pandas to access and view data

<h2>Table of Contents</h2>
<div class="alert alert-block alert-info" style="margin-top: 20px">
    <ul>
        <li><a href="#About-the-Dataset">About the Dataset</a></li>
        <li><a href="#Introduction-of-Pandas">Introduction of <code>Pandas</code></a></li>
        <li><a href="#Viewing-Data-and-Accessing-Data">Viewing Data and Accessing Data</a></li>
        <li><a href="#Quiz-on-DataFrame">Quiz on DataFrame</a></li>
    </ul>

</div>

<hr>

## About the Dataset

The table has one row for each album and several columns.

<ul>
    <li><b>artist</b>: Name of the artist</li>
    <li><b>album</b>: Name of the album</li>
    <li><b>released_year</b>: Year the album was released</li>
    <li><b>length_min_sec</b>: Length of the album (hours,minutes,seconds)</li>
    <li><b>genre</b>: Genre of the album</li>
    <li><b>music_recording_sales_millions</b>: Music recording sales (millions in USD) on <a href="http://www.song-database.com/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork19487395-2021-01-01?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork19487395-2021-01-01">[SONG://DATABASE]</a></li>
    <li><b>claimed_sales_millions</b>: Album's claimed sales (millions in USD) on <a href="http://www.song-database.com/">[SONG://DATABASE]</a></li>
    <li><b>date_released</b>: Date on which the album was released</li>
    <li><b>soundtrack</b>: Indicates if the album is the movie soundtrack (Y) or (N)</li>
    <li><b>rating_of_friends</b>: Indicates the rating from your friends from 1 to 10</li>
</ul>

You can see the dataset here:

<font size="1">
<table font-size:xx-small>
  <tr>
    <th>Artist</th>
    <th>Album</th>
    <th>Released</th>
    <th>Length</th>
    <th>Genre</th>
    <th>Music recording sales (millions)</th>
    <th>Claimed sales (millions)</th>
    <th>Released</th>
    <th>Soundtrack</th>
    <th>Rating (friends)</th>
  </tr>
  <tr>
    <td>Michael Jackson</td>
    <td>Thriller</td>
    <td>1982</td>
    <td>00:42:19</td>
    <td>Pop, rock, R&B</td>
    <td>46</td>
    <td>65</td>
    <td>30-Nov-82</td>
    <td></td>
    <td>10.0</td>
  </tr>
  <tr>
    <td>AC/DC</td>
    <td>Back in Black</td>
    <td>1980</td>
    <td>00:42:11</td>
    <td>Hard rock</td>
    <td>26.1</td>
    <td>50</td>
    <td>25-Jul-80</td>
    <td></td>
    <td>8.5</td>
  </tr>
    <tr>
    <td>Pink Floyd</td>
    <td>The Dark Side of the Moon</td>
    <td>1973</td>
    <td>00:42:49</td>
    <td>Progressive rock</td>
    <td>24.2</td>
    <td>45</td>
    <td>01-Mar-73</td>
    <td></td>
    <td>9.5</td>
  </tr>
    <tr>
    <td>Whitney Houston</td>
    <td>The Bodyguard</td>
    <td>1992</td>
    <td>00:57:44</td>
    <td>Soundtrack/R&B, soul, pop</td>
    <td>26.1</td>
    <td>50</td>
    <td>25-Jul-80</td>
    <td>Y</td>
    <td>7.0</td>
  </tr>
    <tr>
    <td>Meat Loaf</td>
    <td>Bat Out of Hell</td>
    <td>1977</td>
    <td>00:46:33</td>
    <td>Hard rock, progressive rock</td>
    <td>20.6</td>
    <td>43</td>
    <td>21-Oct-77</td>
    <td></td>
    <td>7.0</td>
  </tr>
    <tr>
    <td>Eagles</td>
    <td>Their Greatest Hits (1971-1975)</td>
    <td>1976</td>
    <td>00:43:08</td>
    <td>Rock, soft rock, folk rock</td>
    <td>32.2</td>
    <td>42</td>
    <td>17-Feb-76</td>
    <td></td>
    <td>9.5</td>
  </tr>
    <tr>
    <td>Bee Gees</td>
    <td>Saturday Night Fever</td>
    <td>1977</td>
    <td>1:15:54</td>
    <td>Disco</td>
    <td>20.6</td>
    <td>40</td>
    <td>15-Nov-77</td>
    <td>Y</td>
    <td>9.0</td>
  </tr>
    <tr>
    <td>Fleetwood Mac</td>
    <td>Rumours</td>
    <td>1977</td>
    <td>00:40:01</td>
    <td>Soft rock</td>
    <td>27.9</td>
    <td>40</td>
    <td>04-Feb-77</td>
    <td></td>
    <td>9.5</td>
  </tr>
</table></font>

<hr>

## Introduction of <code>Pandas</code>

In [1]:
# Import required library

import pandas as pd

After the import command, we now have access to a large number of pre-built classes and functions. This assumes the library is installed; in our lab environment all the necessary libraries are installed. One way pandas allows you to work with data is a dataframe. Let's go through the process to go from a comma separated values (<b>.csv</b>) file to a dataframe. This variable <code>csv_path</code> stores the path of the <b>.csv</b>, that is  used as an argument to the <code>read_csv</code> function. The result is stored in the object <code>df</code>, this is a common short form used for a variable referring to a Pandas dataframe.

In [3]:
# Read data from CSV file

# csv_path = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%204/data/TopSellingAlbums.csv'
# df = pd.read_csv(csv_path)
import pandas as pd

filename = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%204/data/TopSellingAlbums.csv"
df = pd.read_csv(filename) #df = pd.read_csv("TopSellingAlbums.csv") # or manually save the dataset from the above link and run the code

We can use the method <code>head()</code> to examine the first five rows of a dataframe:

In [4]:
# Print first five rows of the dataframe

df.head()

,Artist,Album,Released,Length,Genre,Music Recording Sales (millions),Claimed Sales (millions),Released.1,Soundtrack,Rating
0,Michael Jackson,Thriller,1982,0:42:19,"pop, rock, R&B",46.0,65,30-Nov-82,NaN,10.0
1,AC/DC,Back in Black,1980,0:42:11,hard rock,26.1,50,25-Jul-80,NaN,9.5
2,Pink Floyd,The Dark Side of the Moon,1973,0:42:49,progressive rock,24.2,45,01-Mar-73,NaN,9.0
3,Whitney Houston,The Bodyguard,1992,0:57:44,"R&B, soul, pop",27.4,44,17-Nov-92,Y,8.5
4,Meat Loaf,Bat Out of Hell,1977,0:46:33,"hard rock, progressive rock",20.6,43,21-Oct-77,NaN,8.0

We use the path of the excel file and the function <code>read_excel</code>. The result is a data frame as before:

In [5]:
# Read data from Excel File and print the first five rows

xlsx_path = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/jupyterlite/files/Module%205/data/TopSellingAlbums.xlsx'

df = pd.read_excel(xlsx_path)#pd.read_excel("TopSellingAlbums.xlsx")
df.head()

,Artist,Album,Released,Length,Genre,Music Recording Sales (millions),Claimed Sales (millions),Released.1,Soundtrack,Rating
0,Michael Jackson,Thriller,1982,00:42:19,"pop, rock, R&B",46.0,65,1982-11-30,NaN,10.0
1,AC/DC,Back in Black,1980,0:42:11,hard rock,26.1,50,1980-07-25,NaN,9.5
2,Pink Floyd,The Dark Side of the Moon,1973,0:42:49,progressive rock,24.2,45,1973-03-01,NaN,9.0
3,Whitney Houston,The Bodyguard,1992,0:57:44,"R&B, soul, pop",27.4,44,1992-11-17,Y,8.5
4,Meat Loaf,Bat Out of Hell,1977,0:46:33,"hard rock, progressive rock",20.6,43,1977-10-21,NaN,8.0

We can access the column <b>Length</b> and assign it a new dataframe <b>x</b>:

In [6]:
# Access to the column Length

x = df[['Length']]
x

     Length
0  00:42:19
1   0:42:11
2   0:42:49
3   0:57:44
4   0:46:33
5   0:43:08
6  01:15:54
7   0:40:01

The process is shown in the figure:

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%204/images/DataEgOne.png" width="750">

<hr>

## Viewing Data and Accessing Data

You can also get a column as a series. You can think of a Pandas series as a 1-D dataframe. Just use one bracket:

In [7]:
# Get the column as a series

x = df['Length']
x

0    00:42:19
1     0:42:11
2     0:42:49
3     0:57:44
4     0:46:33
5     0:43:08
6    01:15:54
7     0:40:01
Name: Length, dtype: object

You can also get a column as a dataframe. For example, we can assign the column <b>Artist</b>:

In [8]:
# Get the column as a dataframe

x = df[['Artist']]
type(x)

pandas.core.frame.DataFrame

You can do the same thing for multiple columns; we just put the dataframe name, in this case, <code>df</code>, and the name of the multiple column headers enclosed in double brackets. The result is a new dataframe comprised of the specified columns:

In [9]:
# Access to multiple columns

y = df[['Artist','Length','Genre']]
y

            Artist    Length                        Genre
0  Michael Jackson  00:42:19               pop, rock, R&B
1            AC/DC   0:42:11                    hard rock
2       Pink Floyd   0:42:49             progressive rock
3  Whitney Houston   0:57:44               R&B, soul, pop
4        Meat Loaf   0:46:33  hard rock, progressive rock
5           Eagles   0:43:08   rock, soft rock, folk rock
6         Bee Gees  01:15:54                        disco
7    Fleetwood Mac   0:40:01                    soft rock

The process is shown in the figure:

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%204/images/DataEgTwo.png" width="1100">

One way to access unique elements is the <code>iloc</code> method, where you can access the 1st row and the 1st column as follows:

In [10]:
# Access the value on the first row and the first column

df.iloc[0, 0]

'Michael Jackson'

You can access the 2nd row and the 1st column as follows:

In [11]:
# Access the value on the second row and the first column

df.iloc[1,0]

'AC/DC'

You can access the 1st row and the 3rd column as follows:

In [12]:
# Access the value on the first row and the third column

df.iloc[0,2]

np.int64(1982)

In [13]:
# Access the value on the second row and the third column
df.iloc[1,2]

np.int64(1980)

This is shown in the following image

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%204/images/2_loc.PNG" width="750">

You can access the column using the name as well, the following are the same as above:

In [14]:
# Access the column using the name

df.loc[1, 'Artist']

'AC/DC'

In [15]:
# Access the column using the name

df.loc[1, 'Artist']

'AC/DC'

In [16]:
# Access the column using the name

df.loc[0, 'Released']

np.int64(1982)

In [17]:
# Access the column using the name

df.loc[1, 'Released']

np.int64(1980)

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%204/images/1_loc.png" width="750">

You can perform slicing using both the index and the name of the column:

In [18]:
# Slicing the dataframe

df.iloc[0:2, 0:3]

            Artist          Album  Released
0  Michael Jackson       Thriller      1982
1            AC/DC  Back in Black      1980

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%204/images/4_loc.png" width="750">

In [19]:
# Slicing the dataframe using name

df.loc[0:2, 'Artist':'Released']

            Artist                      Album  Released
0  Michael Jackson                   Thriller      1982
1            AC/DC              Back in Black      1980
2       Pink Floyd  The Dark Side of the Moon      1973

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%204/images/3_loc.png" width="750">

<hr>

## Quiz on DataFrame

Use a variable <code>q</code> to store the column <b>Rating</b> as a dataframe

In [22]:
# Write your code below and press Shift+Enter to execute
# Store the 'Rating' column as a DataFrame
q = df[['Rating']]

# Check the result
print(q)

   Rating
0    10.0
1     9.5
2     9.0
3     8.5
4     8.0
5     7.5
6     7.0
7     6.5

Assign the variable <code>q</code> to the dataframe that is made up of the column <b>Released</b> and <b>Artist</b>:

In [23]:
# Write your code below and press Shift+Enter to execute
# Store 'Released' and 'Artist' columns as a DataFrame in q
q = df[['Released', 'Artist']]

# Check the result
print(q)

   Released           Artist
0      1982  Michael Jackson
1      1980            AC/DC
2      1973       Pink Floyd
3      1992  Whitney Houston
4      1977        Meat Loaf
5      1976           Eagles
6      1977         Bee Gees
7      1977    Fleetwood Mac

Access the 2nd row and the 3rd column of <code>df</code>:

In [24]:
# Write your code below and press Shift+Enter to execute
# Access 2nd row (index 1) and 3rd column (index 2)
value = df.iloc[1, 2]

print(value)

1980

Use the following list to convert the dataframe index <code>df</code> to characters and assign it to <code>df_new</code>; find the element corresponding to the row index <code>a</code> and column  <code>'Artist'</code>. Then select the rows <code>a</code> through <code>d</code> for the column  <code>'Artist'</code>

In [25]:

new_index = ['a','b','c','d','e','f','g','h']

# Step 2: Assign the new index to df and create df_new
df_new = df.copy()       # make a copy to avoid changing original df
df_new.index = new_index

# Step 3: Access the element at row 'a' and column 'Artist'
artist_a = df_new.loc['a', 'Artist']
print("Artist at row 'a':", artist_a)

# Step 4: Select rows 'a' through 'd' for the column 'Artist'
artists_a_to_d = df_new.loc['a':'d', 'Artist']
print("\nArtists from row 'a' to 'd':\n", artists_a_to_d)

Artist at row 'a': Michael Jackson

Artists from row 'a' to 'd':
 a    Michael Jackson
b              AC/DC
c         Pink Floyd
d    Whitney Houston
Name: Artist, dtype: object